version: '3'

services:
  database:
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql:nocopy

  php-fpm:
    volumes:
      - src:/var/www:nocopy

  nginx:
    volumes:
      - src:/var/www:nocopy
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log:delegated

volumes:
    db:
      external: true
    src:
      external: true


